#!/bin/bash

echo "🚀 HTML to Figma Plugin - Render Deployment Guide"
echo "================================================="

echo "✅ Backend optimized for Render deployment"
echo "✅ Regular Puppeteer (no serverless complications)"
echo "✅ Network access configured for *.onrender.com"
echo ""

echo "📋 Deployment Steps:"
echo ""
echo "1. 🌐 Go to https://render.com and sign up"
echo ""
echo "2. 🔗 Choose Deployment Method:"
echo ""
echo "   Option A - Auto-Deploy (Recommended):"
echo "   - Click 'New +' → 'Blueprint'"
echo "   - Connect your GitHub repository"
echo "   - Render detects render.yaml automatically"
echo ""
echo "   Option B - Manual Setup:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect your GitHub repository"
echo "   - Configure manually:"
echo "     * Name: html-to-figma-backend"
echo "     * Root Directory: backend"
echo "     * Environment: Node"
echo "     * Build Command: npm install"
echo "     * Start Command: npm start"
echo "     * Plan: Starter (Free)"
echo ""
echo "3. 🚀 Deploy:"
echo "   - Click 'Create Web Service' or 'Deploy Blueprint'"
echo "   - Wait for deployment (2-3 minutes)"
echo "   - Copy your URL (e.g., https://html-to-figma-backend.onrender.com)"
echo ""
echo "5. 🔧 Update Plugin:"
echo "   - Edit code.js"
echo "   - Update BACKEND_URL with your Render URL"
echo "   - Save and reimport plugin in Figma"
echo ""
echo "6. 🧪 Test:"
echo "   - Update BACKEND_URL in code.js first"
echo "   - Run: node test-deployment.js"
echo ""

echo "💡 Why Render?"
echo "   ✅ Perfect for Puppeteer (no Chrome issues)"
echo "   ✅ Full Linux environment"
echo "   ✅ Free tier available"
echo "   ✅ Simple deployment"
echo "   ✅ No serverless limitations"
echo ""

echo "📚 Documentation:"
echo "   - Complete guide: RENDER_DEPLOYMENT.md"
echo "   - Troubleshooting: Check Render dashboard logs"
echo ""

echo "🎉 Render is the easiest way to deploy Puppeteer apps!"
echo "   No configuration headaches, just works! 🚀"
